# 格納する際はkubesecなどで
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
data:
  # cat ~/.id_rs | base64 -w 0
  ssh-privatekey: <base64 encoded>
  # This is non-standard, but its use is encouraged to make this more secure.
  # ssh-keyscan github.com | base64 -w 0
  #known_hosts: <base64 encoded>
---
# for infra repo update
# for git webhook
apiVersion: v1
kind: Secret
metadata:
  name: git-secret
data:
  GIT_TOKEN: xxxxx
  apisecret: mypipelinesecret
