apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-update
spec:
  resources:
    - name: git-apprepo
      type: git
    - name: git-infrarepo
      type: git
    - name: image
      type: image
  params:
    - name: deployment-name
      type: string
      description: name of the deployment to be patched
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
    - name: commithash
      description: commit hash
    - name: imageUrl
      description: Url of image repository
    - name: imageTag
      description: Tag to apply to the built image
  tasks:

  - name: update
    taskRef:
      name: update-manifest
    params:
      - name: pathToYamlFile
        value:  "$(params.pathToYamlFile)"
      - name: commithash
        value: "$(params.commithash)"
      - name: imageUrl
        value: "$(params.imageUrl)"
      - name: imageTag
        value: "$(params.imageTag)"
    resources:
      inputs:
        - name: git-source
          resource: git-infrarepo


  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    resources:
      inputs:
      - name: source
        resource: git-apprepo
      outputs:
      - name: image
        resource: image
    params:
    - name: TLSVERIFY
      value: "false"