apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: manifest-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/unkogero/pipelinetest
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/unkogero/actionstest
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-image
spec:
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/pipelinens/app
  type: image