apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: update-manifest
spec:
  inputs:
    resources:
      - name: git-source
        type: git
      - name: image
        type: image
    params:
      - name: pathToYamlFile
        description: The path to the yaml file to deploy within the git source
      - name: commithash
        description: commit hash
  steps:
    #- name: update-yaml
    #  image: alpine
    #  command: ["sed"]
    #  args:
    #    - "-i"
    #    - "-e"
    #    - "s;__IMAGE__;$(inputs.resources.image.url);g"
    #    - "/workspace/git-source/$(inputs.params.pathToYamlFile)"

    - name: echo
      image: bash:latest
      script: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

        cd testapp/overlays/prd
        kustomize edit set image image-name=$(inputs.resources.image.url)

    - name: push
      image: alpine/git:v2.24.3
      script: |
        echo "push"
        cd /workspace/git-source

        git config --local user.email "tekton@xxx.com"
        git config --local user.name "tekton task"
        #git config remote.origin.url "git@github.com:unkogero/pipelinetest.github.io.git"

        git checkout -b tekton
        git add .
        git commit -m "auto commit"

        git push origin tekton
