apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: update-manifest

spec:
  params:
    - description: The path to the yaml file to deploy within the git source
      name: pathToYamlFile
      type: string
    - description: commit hash
      name: commithash
      type: string
  resources:
    inputs:
      - name: git-source
        type: git
      - name: image
        type: image
  steps:
    - image: 'byrnedo/alpine-curl'
      name: request
      resources: {}
      script: |
        echo $GIT_TOKEN
        curl -XPOST \
        -H "Authorization: token "${GIT_TOKEN} \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/unkogero/pipelinetest/actions/workflows/merge.yml/dispatches \
        -d '{"ref":"master","inputs": {"imagename":"'$(inputs.resources.image.url)'"}}'
      env:
      - name: GIT_TOKEN
        valueFrom:
          secretKeyRef:
            name: git-secret
            key: GIT_TOKEN
  volumes:
  - name: git-secret
    secret:
      secretName: git-secret