name: merge

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  merge:
    runs-on: ubuntu-latest
    env:
      REF: ${{github.event.pull_request.head.ref}}
      HASH: ${{ github.sha }}
      TOKEN: ${{secrets.TKN}}
      REPO: https://x-access-token:${{secrets.TKN}}@github.com/unkogero/pipelinetest.git
    steps:
      - uses: actions/checkout@v2
        with:
          repository: unkogero/pipelinetest
          ref: master
        #  token: ${TOKEN}
      - run: date >> README.md
      - name: commit manifests and push
        run: |
          echo ${REF}
          sed -ie "s/__IMAGE__/imageurl:imagetag:${HASH}/g" manifest/k8s.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
