# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
    types: synchronize
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: post request
      env:
          URL: ${{ secrets.TARGET_URL }}
          REPO: ${{ github.repository }}
      run: |
        curl -X POST \
             -d "{\"body\": \"${REPO}\"}" \
             ${URL}