# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: sendreq

on:
  push:
    branches:
      - main

jobs:
  send_req:

    runs-on: ubuntu-latest

    steps:
    - name: post request
      env:
          URL: https://webhook.site/3e92780e-4d01-4c99-ae6d-f6ecf75bf9b0
          SECURL: ${{ secrets.TARGET_URL }}
          REPO: ${{ github.repository }}
          HASH: ${{ github.sha }}
          REF: ${{ github.ref }}
          ACTOR: ${{ github.actor }}
      run: |
        echo url=${URL}
        echo securl=${SECURL}
        echo repo=${REPO}
        curl -X POST \
             -d "{\"body\": \"sendmessage\",
              \"hash\":${HASH},
              \"repo\":${REPO},
              \"ref\":${REF},
              \"actor\":${ACTOR}
              }" \
             ${URL} -f